# environment and task
env:
  nu: 0.05
  num_actuators: 20
  num_sensors: 256
  actuator_scale: 0.1
  N: 256
  dt: 0.05
  num_envs: 3  # Number of parallel training envs
  burnin: 10000
  target:
  exp_name: KS
  path_to_cae_model:  # if empty or None, no trained autoencoder will be used
  frame_skip: 1  # Sticky actions
  soft_action: True  # Interpolate the actions over frame_skip frames
  autoreg_action: 0.0  # Autoregressive action hyperparameter
  seed: 2253461632  # keep fixed for now
  auto_generate_seed: True  # If True, generate a random seed. If False, use the seed value specified above.

# collector
collector:
  frames_per_batch: 1_000 # this is the actual number of frames we see in a batch
  max_episode_length: 1_000  # Timesteps (disregarding frame skip)
  total_frames: 500_000  # Timesteps (disregarding frame skip)
  device: cpu

# logger
logger:
  backend: wandb
  mode: online
  eval_iter: 10  # Evaluate every x batches
  test_episode_length: 1_000
  project_name: LatentRL
  team_name: why_are_all_the_good_names_taken_aaa
  save_replay_buffer: False

# Optim
optim:
  lr: 1e-4
  weight_decay: 0.0
  anneal_lr: True

# loss
loss:
  gamma: 0.9
  mini_batch_size: 25  # must be less than frames per batch
  ppo_epochs: 10
  gae_lambda: 0.95
  clip_epsilon: 0.2
  anneal_clip_epsilon: False
  critic_coef: 0.25
  entropy_coef: 0.0
  loss_critic_type: l2

# Disable output subdirectory
hydra:
  output_subdir: config
