apiVersion: batch/v1
kind: Job
metadata:
 generateName: ks-ppo-
 labels:
   kueue.x-k8s.io/queue-name: eidf079ns-user-queue
spec:
 completions: 1
 parallelism: 1
 template:
  spec:
   restartPolicy: Never
   containers:
   - name: pytorch-con
     image: pytorch/pytorch:2.1.0-cuda12.1-cudnn8-devel
     volumeMounts:
      - mountPath: /dev/shm
        name: dshm
     command: [/bin/bash, -c, --]
     args: 
       - |
         export OMP_NUM_THREADS=1;
         mkdir build;
         cd build;
         apt update; apt upgrade -y; apt install git vim -y;
         git clone https://github.com/maxweissenbacher/latentRL.git;
         cd latentRL;
         git checkout rl;
         pip install -r requirements.txt;
         wandb login ac8ec66b318e6624089b2723c3174f01a850416c;
         python main.py
     resources:
      requests:
       cpu: 8
       memory: "64Gi"
      limits:
       cpu: 8
       memory: "64Gi"
       nvidia.com/gpu: 1
   nodeSelector:
    nvidia.com/gpu.product: NVIDIA-A100-SXM4-40GB
   volumes:
   - name: dshm
     emptyDir:
      medium: Memory
